In [4]:
from PIL import Image
import numpy as np
import sys
import os
import csv

#Useful function
def createFileList(myDir, format='.jpg'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('/Users/sunying/Desktop/db3/full/jpg/')

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("/Users/sunying/Desktop/file1.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)

/Users/sunying/Desktop/db3/full/jpg/
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00010_LEFT_MLO.jpg
[255 255 255 ... 228 229 228]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00024_LEFT_CC.jpg
[  0   0   0 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/0+Calc-Training_P_00078_LEFT_MLO.jpg
[165 164 162 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00030_RIGHT_MLO.jpg
[236 237 237 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00048_RIGHT_CC.jpg
[236 235 235 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/0+Calc-Training_P_00088_LEFT_CC.jpg
[ 0  0  0 ... 43 46 44]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00123_LEFT_CC.jpg
[255 255 255 ...   4   2   4]
/Users/sunying/Desktop/db3/full/jpg/0+Calc-Training_P_00047_LEFT_CC.jpg
[255 255 255 ... 236 235 236]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00008_RIGHT_CC.jpg
[113 112 107 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Tr

[255 255 255 ... 236 235 235]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00112_RIGHT_MLO.jpg
[212 213 212 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00019_RIGHT_CC.jpg
[ 20  26 255 ...   0   0   0]
/Users/sunying/Desktop/db3/full/jpg/0+Calc-Training_P_00063_RIGHT_CC.jpg
[ 62  60  58 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/0+Calc-Training_P_00157_LEFT_CC.jpg
[255 255 255 ... 235 237 237]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00007_LEFT_MLO.jpg
[ 70  72  74 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00106_RIGHT_MLO.jpg
[237 237 237 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00083_RIGHT_CC.jpg
[255   0 255 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00011_LEFT_CC.jpg
[  0   0   0 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc-Training_P_00008_RIGHT_MLO.jpg
[235 236 236 ... 255 255 255]
/Users/sunying/Desktop/db3/full/jpg/1+Calc